### ISSUE TITLE
client-apps.js fails to start

### ISSUE THREAD

**Issue by theodotos** [rcpeters/simple-orcid-auth-node#3]
Hello,

I am trying to install this on Ubuntu 14.04. These are my steps up to now:
### Installation:
- `apt -y install node nodejs npm`
- `wget https://github.com/rcpeters/simple-orcid-auth-node/archive/master.tar.gz`
- `tar xvzf master.tar.gz -C /var/www/`
- `cd /var/www/`
- `mv simple-orcid-auth-node-master/ orcid`
- `cd orcid`
- `npm install`
### Configuring ORCID:
- Edit helpers/config.js: 
  
  ```
      module.exports = config = {
            // Config for OAuth2   
            CLIENT_ID: 'APP-HSGSHJS335353GSGSG',
            CLIENT_SECRET: '56d4eb21-6622-8483-3422-f53f3fs53sfs35f',
            AUTHORIZE_URI: 'https://sandbox.orcid.org/oauth/authorize',
            TOKEN_EXCHANGE_URI: 'https://api.sandbox.orcid.org/oauth/token',
            CODE_CALLBACK_URI: 'http://orcid.example.com:8000/authorization-code-callback',
            // General server config
            PORT: '8000',
            SERVER_IP: '10.2.2.2',
          }
  
          // Environment variables overrides
          for (key in config)
                       if (process.env[key] != undefined)
                                   config[key] = process.env[key];
  
          // www.openshift.com deployment overrides
          if (process.env.OPENSHIFT_NODEJS_IP != undefined)
                     config.SERVER_IP = process.env.OPENSHIFT_NODEJS_IP;
          if (process.env.OPENSHIFT_NODEJS_PORT != undefined)
                     config.PORT = process.env.OPENSHIFT_NODEJS_PORT;
  ```
### Start client application:
- `node client-app.js`

**NOTE: App does not start. Exit code is '1'. No error messages!**

```
node ./client-app.js ; echo $?`
1
```

How can I troubleshout this further?

**Comment by rcpeters** [comment]
Hi Theodotos,
I just tested on 14.04 the application started fine. The information
provided doesn't give me place to start. Try making a hello world
http://expressjs.com/en/starter/hello-world.html and see what happens.

Cheers,
Rob

On Tue, Apr 26, 2016 at 4:00 AM, Theodotos Andreou <notifications@github.com

> wrote:
> 
> Hello,
> 
> I am trying to install this on Ubuntu 14.04. These are my steps up to now:
> Installation:
> - apt -y install node nodejs npm
> - wget
>   https://github.com/rcpeters/simple-orcid-auth-node/archive/master.tar.gz
> - tar xvzf master.tar.gz -C /var/www/
> - cd /var/www/
> - mv simple-orcid-auth-node-master/ orcid
> - cd orcid
> - npm install
> 
> Configuring ORCID:
> 
>    -
> 
>    Edit helpers/config.js:
> 
> ```
>    module.exports = config = {
>          // Config for OAuth2
>          CLIENT_ID: 'APP-HSGSHJS335353GSGSG',
>          CLIENT_SECRET: '56d4eb21-6622-8483-3422-f53f3fs53sfs35f',
>          AUTHORIZE_URI: 'https://sandbox.orcid.org/oauth/authorize',
>          TOKEN_EXCHANGE_URI: 'https://api.sandbox.orcid.org/oauth/token',
>          CODE_CALLBACK_URI: 'http://orcid.example.com:8000/authorization-code-callback',
>          // General server config
>          PORT: '8000',
>          SERVER_IP: '10.2.2.2',
>        }
> 
>        // Environment variables overrides
>        for (key in config)
>                     if (process.env[key] != undefined)
>                                 config[key] = process.env[key];
> 
>        // www.openshift.com deployment overrides
>        if (process.env.OPENSHIFT_NODEJS_IP != undefined)
>                   config.SERVER_IP = process.env.OPENSHIFT_NODEJS_IP;
>        if (process.env.OPENSHIFT_NODEJS_PORT != undefined)
>                   config.PORT = process.env.OPENSHIFT_NODEJS_PORT;
> ```
> 
> Start client application:
> - node client-app.js
> 
> _NOTE: App does not start. Exit code is '1'. No error messages!_
> 
> node ./client-app.js ; echo $?`
> 1
> 
> How can I troubleshout this further?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ORCID/simple-orcid-auth-node/issues/3

## 

Robert Peters
info@rcpeters.com
805.440.9056

**Comment by theodotos** [comment]
You are right! It looks like the package 'node' is a dummy package that installs 'ax25-node'. This is a package for amateur radio and completely unrelated with nodejs.

The solution was to install 'nodejs-legacy'

Sorry for the false alarm.
